export const APPEARANCE_COLORS: { name: string; hex: string }[] = [
  { name: 'red', hex: '#ff6b6b' },
  { name: 'orange', hex: '#fd9644' },
  { name: 'yellow', hex: '#ffd43b' },
  { name: 'lime', hex: '#a9e34b' },
  { name: 'green', hex: '#51cf66' },
  { name: 'teal', hex: '#20c997' },
  { name: 'blue', hex: '#4dabf7' },
  { name: 'violet', hex: '#cc5de8' },
];

export const APPEARANCE_ICONS: { name: string; codicon: string }[] = [
  { name: 'Grid', codicon: 'codicon-layout' },
  { name: 'Circle', codicon: 'codicon-circle-large' },
  { name: 'Triangle', codicon: 'codicon-triangle-up' },
  { name: 'Square', codicon: 'codicon-primitive-square' },
  { name: 'Diamond', codicon: 'codicon-symbol-event' },
  { name: 'Hexagon', codicon: 'codicon-symbol-misc' },
  { name: 'Star', codicon: 'codicon-star-full' },
  { name: 'Heart', codicon: 'codicon-heart' },
  { name: 'Flame', codicon: 'codicon-flame' },
  { name: 'Rocket', codicon: 'codicon-rocket' },
  { name: 'Cloud', codicon: 'codicon-cloud' },
  { name: 'Lightbulb', codicon: 'codicon-lightbulb' },
  { name: 'Lock', codicon: 'codicon-lock' },
  { name: 'Key', codicon: 'codicon-key' },
  { name: 'Shield', codicon: 'codicon-shield' },
  { name: 'Wrench', codicon: 'codicon-wrench' },
  { name: 'Hammer', codicon: 'codicon-tools' },
  { name: 'Gear', codicon: 'codicon-gear' },
  { name: 'Globe', codicon: 'codicon-globe' },
  { name: 'Database', codicon: 'codicon-database' },
  { name: 'Beaker', codicon: 'codicon-beaker' },
  { name: 'Bug', codicon: 'codicon-bug' },
  { name: 'Bookmark', codicon: 'codicon-bookmark' },
  { name: 'Tag', codicon: 'codicon-tag' },
];
