/**
 * Comprehensive list of common HTTP headers for autocomplete.
 * Alphabetically sorted for optimal UX in datalist dropdown.
 */
export const COMMON_HTTP_HEADERS = [
	'A-IM',
	'Accept',
	'Accept-Charset',
	'Accept-Datetime',
	'Accept-Encoding',
	'Accept-Language',
	'Accept-Patch',
	'Accept-Ranges',
	'Access-Control-Allow-Credentials',
	'Access-Control-Allow-Headers',
	'Access-Control-Allow-Methods',
	'Access-Control-Allow-Origin',
	'Access-Control-Expose-Headers',
	'Access-Control-Max-Age',
	'Access-Control-Request-Headers',
	'Access-Control-Request-Method',
	'Age',
	'Allow',
	'Alt-Svc',
	'Authorization',
	'Cache-Control',
	'Connection',
	'Content-Disposition',
	'Content-Encoding',
	'Content-Language',
	'Content-Length',
	'Content-Location',
	'Content-MD5',
	'Content-Range',
	'Content-Security-Policy',
	'Content-Security-Policy-Report-Only',
	'Content-Type',
	'Cookie',
	'DNT',
	'Date',
	'ETag',
	'Early-Data',
	'Expect',
	'Expect-CT',
	'Expires',
	'Forwarded',
	'From',
	'Host',
	'If-Match',
	'If-Modified-Since',
	'If-None-Match',
	'If-Range',
	'If-Unmodified-Since',
	'Keep-Alive',
	'Large-Allocation',
	'Last-Modified',
	'Link',
	'Location',
	'Max-Forwards',
	'NEL',
	'Origin',
	'Pragma',
	'Proxy-Authenticate',
	'Proxy-Authorization',
	'Proxy-Connection',
	'Public-Key-Pins',
	'Public-Key-Pins-Report-Only',
	'Range',
	'Referer',
	'Referrer-Policy',
	'Retry-After',
	'Save-Data',
	'Sec-CH-UA',
	'Sec-CH-UA-Mobile',
	'Sec-CH-UA-Platform',
	'Sec-Fetch-Dest',
	'Sec-Fetch-Mode',
	'Sec-Fetch-Site',
	'Sec-Fetch-User',
	'Sec-WebSocket-Accept',
	'Sec-WebSocket-Extensions',
	'Sec-WebSocket-Key',
	'Sec-WebSocket-Protocol',
	'Sec-WebSocket-Version',
	'Server',
	'Server-Timing',
	'Set-Cookie',
	'SourceMap',
	'Strict-Transport-Security',
	'TE',
	'Timing-Allow-Origin',
	'Tk',
	'Trailer',
	'Transfer-Encoding',
	'Upgrade',
	'Upgrade-Insecure-Requests',
	'User-Agent',
	'Vary',
	'Via',
	'WWW-Authenticate',
	'Warning',
	'X-API-Key',
	'X-ATT-DeviceId',
	'X-Amz-Date',
	'X-Amz-Security-Token',
	'X-Azure-Ref',
	'X-CSRF-Token',
	'X-Client-Data',
	'X-Cloud-Trace-Context',
	'X-Content-Duration',
	'X-Content-Security-Policy',
	'X-Content-Type-Options',
	'X-Correlation-ID',
	'X-DNS-Prefetch-Control',
	'X-Download-Options',
	'X-Forwarded-For',
	'X-Forwarded-Host',
	'X-Forwarded-Port',
	'X-Forwarded-Proto',
	'X-Frame-Options',
	'X-HTTP-Method-Override',
	'X-Permitted-Cross-Domain-Policies',
	'X-Pingback',
	'X-RateLimit-Limit',
	'X-RateLimit-Remaining',
	'X-RateLimit-Reset',
	'X-Real-IP',
	'X-Request-ID',
	'X-Requested-With',
	'X-UA-Compatible',
	'X-UIDH',
	'X-Wap-Profile',
	'X-WebKit-CSP',
	'X-XSS-Protection',
] as const;

/**
 * Headers organized by category for future reference/documentation.
 * Not exported for autocomplete (use COMMON_HTTP_HEADERS instead).
 */
export const HTTP_HEADERS_BY_CATEGORY = {
	// Standard Request Headers
	request: [
		'Accept',
		'Accept-Charset',
		'Accept-Encoding',
		'Accept-Language',
		'Authorization',
		'Cache-Control',
		'Connection',
		'Cookie',
		'Content-Length',
		'Content-Type',
		'Date',
		'Expect',
		'From',
		'Host',
		'If-Match',
		'If-Modified-Since',
		'If-None-Match',
		'If-Range',
		'If-Unmodified-Since',
		'Max-Forwards',
		'Origin',
		'Pragma',
		'Proxy-Authorization',
		'Range',
		'Referer',
		'TE',
		'Upgrade',
		'User-Agent',
		'Via',
	],

	// Standard Response Headers
	response: [
		'Accept-Ranges',
		'Age',
		'Allow',
		'Alt-Svc',
		'Cache-Control',
		'Connection',
		'Content-Disposition',
		'Content-Encoding',
		'Content-Language',
		'Content-Length',
		'Content-Location',
		'Content-MD5',
		'Content-Range',
		'Content-Type',
		'Date',
		'ETag',
		'Expires',
		'Last-Modified',
		'Link',
		'Location',
		'Proxy-Authenticate',
		'Retry-After',
		'Server',
		'Set-Cookie',
		'Trailer',
		'Transfer-Encoding',
		'Upgrade',
		'Vary',
		'Via',
		'WWW-Authenticate',
		'Warning',
	],

	// CORS Headers
	cors: [
		'Access-Control-Allow-Credentials',
		'Access-Control-Allow-Headers',
		'Access-Control-Allow-Methods',
		'Access-Control-Allow-Origin',
		'Access-Control-Expose-Headers',
		'Access-Control-Max-Age',
		'Access-Control-Request-Headers',
		'Access-Control-Request-Method',
		'Origin',
	],

	// Security Headers
	security: [
		'Content-Security-Policy',
		'Content-Security-Policy-Report-Only',
		'Expect-CT',
		'Public-Key-Pins',
		'Public-Key-Pins-Report-Only',
		'Referrer-Policy',
		'Strict-Transport-Security',
		'X-Content-Security-Policy',
		'X-Content-Type-Options',
		'X-DNS-Prefetch-Control',
		'X-Download-Options',
		'X-Frame-Options',
		'X-Permitted-Cross-Domain-Policies',
		'X-WebKit-CSP',
		'X-XSS-Protection',
	],

	// Authentication Headers
	auth: [
		'Authorization',
		'Proxy-Authenticate',
		'Proxy-Authorization',
		'WWW-Authenticate',
		'X-API-Key',
		'X-CSRF-Token',
	],

	// Caching Headers
	caching: [
		'Age',
		'Cache-Control',
		'ETag',
		'Expires',
		'If-Match',
		'If-Modified-Since',
		'If-None-Match',
		'If-Range',
		'If-Unmodified-Since',
		'Last-Modified',
		'Pragma',
	],

	// WebSocket Headers
	websocket: [
		'Sec-WebSocket-Accept',
		'Sec-WebSocket-Extensions',
		'Sec-WebSocket-Key',
		'Sec-WebSocket-Protocol',
		'Sec-WebSocket-Version',
		'Upgrade',
	],

	// Performance & Monitoring
	performance: [
		'NEL',
		'Server-Timing',
		'Timing-Allow-Origin',
		'X-Content-Duration',
	],

	// Cloud Provider Headers
	cloud: [
		'X-Amz-Date',
		'X-Amz-Security-Token',
		'X-Azure-Ref',
		'X-Cloud-Trace-Context',
	],

	// Custom/Vendor Headers
	custom: [
		'DNT',
		'Early-Data',
		'Forwarded',
		'Large-Allocation',
		'Save-Data',
		'SourceMap',
		'Tk',
		'Upgrade-Insecure-Requests',
		'X-ATT-DeviceId',
		'X-Client-Data',
		'X-Correlation-ID',
		'X-Forwarded-For',
		'X-Forwarded-Host',
		'X-Forwarded-Port',
		'X-Forwarded-Proto',
		'X-HTTP-Method-Override',
		'X-Pingback',
		'X-RateLimit-Limit',
		'X-RateLimit-Remaining',
		'X-RateLimit-Reset',
		'X-Real-IP',
		'X-Request-ID',
		'X-Requested-With',
		'X-UA-Compatible',
		'X-UIDH',
		'X-Wap-Profile',
	],

	// Client Hints
	clientHints: [
		'Sec-CH-UA',
		'Sec-CH-UA-Mobile',
		'Sec-CH-UA-Platform',
	],

	// Fetch Metadata
	fetchMetadata: [
		'Sec-Fetch-Dest',
		'Sec-Fetch-Mode',
		'Sec-Fetch-Site',
		'Sec-Fetch-User',
	],

	// Content Negotiation
	contentNegotiation: [
		'A-IM',
		'Accept',
		'Accept-Charset',
		'Accept-Datetime',
		'Accept-Encoding',
		'Accept-Language',
		'Accept-Patch',
	],

	// Connection Management
	connection: [
		'Connection',
		'Keep-Alive',
		'Proxy-Connection',
	],
} as const;