/** @type {import('jest').Config} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/*.test.ts'],
  testPathIgnorePatterns: ['/node_modules/'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  collectCoverageFrom: [
    'src/services/StorageService.ts',
    'src/services/FileService.ts',
    'src/services/EnvFileService.ts',
    'src/services/SecretStorageService.ts',
    'src/services/DraftService.ts',
    'src/services/OpenApiImportService.ts',
    'src/services/openapi/**/*.ts',
    'src/providers/OpenApiDiagnosticsManager.ts',
    'src/providers/OpenApiSymbolProvider.ts',
    'src/providers/OpenApiDefinitionProvider.ts',
    'src/providers/OpenApiPreviewPanelManager.ts',
    'src/providers/OpenApiOutlineProvider.ts',
    'src/providers/openapi-outline/**/*.ts',
    'src/commands/openapi.ts',
    'src/commands/openapi-outline.ts',
    'src/services/ImportExportService.ts',
    'src/services/storage/**/*.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  moduleNameMapper: {
    '^vscode$': '<rootDir>/src/test/__mocks__/vscode.ts',
    '^@faker-js/faker$': '<rootDir>/src/test/__mocks__/faker.ts',
  },
  setupFilesAfterEnv: ['<rootDir>/src/test/setup.ts'],
};
