export const EXIT = {
  SUCCESS: 0,
  TEST_FAILURE: 1,
  FILE_NOT_FOUND: 2,
  ENV_NOT_FOUND: 3,
  INVALID_COLLECTION: 4,
  REQUEST_NOT_FOUND: 5,
  IMPORT_FORMAT_ERROR: 6,
  OTHER_ERROR: 7,
} as const;
