import * as fs from 'fs/promises';
import { existsSync } from 'fs';
import * as path from 'path';
import type { IStorageStrategy } from './IStorageStrategy';
import type { Collection, HistoryEntry, EnvironmentsData } from '../types';

export class GitFriendlyStorageStrategy implements IStorageStrategy {
  private readonly collectionsDir: string;
  private readonly historyPath: string;
  private readonly environmentsPath: string;
  private readonly gitignorePath: string;

  constructor(private readonly storageDir: string) {
    this.collectionsDir = path.join(storageDir, 'collections');
    this.historyPath = path.join(storageDir, 'history.json');
    this.environmentsPath = path.join(storageDir, 'environments.json');
    this.gitignorePath = path.join(storageDir, '.gitignore');
  }

  private async ensureDir(): Promise<void> {
    if (!existsSync(this.storageDir)) {
      await fs.mkdir(this.storageDir, { recursive: true });
    }
    if (!existsSync(this.collectionsDir)) {
      await fs.mkdir(this.collectionsDir, { recursive: true });
    }
  }

  async ensureGitignore(): Promise<void> {
    await this.ensureDir();
    const content = '# Auto-generated by HiveFetch\nhistory.json\n';
    if (!existsSync(this.gitignorePath)) {
      await fs.writeFile(this.gitignorePath, content, 'utf8');
    }
  }

  async loadCollections(): Promise<Collection[]> {
    try {
      if (!existsSync(this.collectionsDir)) {
        return [];
      }
      const files = await fs.readdir(this.collectionsDir);
      const jsonFiles = files.filter(f => f.endsWith('.json'));
      const collections: Collection[] = [];

      for (const file of jsonFiles) {
        try {
          const filePath = path.join(this.collectionsDir, file);
          const data = await fs.readFile(filePath, 'utf8');
          const collection = JSON.parse(data) as Collection;
          collections.push(collection);
        } catch (error) {
          console.error(`Failed to load collection from ${file}:`, error);
        }
      }

      // Sort by name for deterministic order
      collections.sort((a, b) => a.name.localeCompare(b.name));
      return collections;
    } catch (error) {
      console.error('Failed to load collections:', error);
      return [];
    }
  }

  async saveCollections(collections: Collection[]): Promise<boolean> {
    try {
      await this.ensureDir();

      // Write each collection to its own file
      const savedIds = new Set<string>();
      for (const collection of collections) {
        const filePath = path.join(this.collectionsDir, `${collection.id}.json`);
        await fs.writeFile(filePath, JSON.stringify(collection, null, 2), 'utf8');
        savedIds.add(collection.id);
      }

      // Delete orphaned files (collections that were removed)
      const existingFiles = await fs.readdir(this.collectionsDir);
      for (const file of existingFiles) {
        if (!file.endsWith('.json')) continue;
        const id = file.replace('.json', '');
        if (!savedIds.has(id)) {
          await fs.unlink(path.join(this.collectionsDir, file));
        }
      }

      return true;
    } catch (error) {
      console.error('Failed to save collections:', error);
      return false;
    }
  }

  async loadHistory(): Promise<HistoryEntry[]> {
    try {
      if (existsSync(this.historyPath)) {
        const data = await fs.readFile(this.historyPath, 'utf8');
        return JSON.parse(data) as HistoryEntry[];
      }
    } catch (error) {
      console.error('Failed to load history:', error);
    }
    return [];
  }

  async saveHistory(history: HistoryEntry[]): Promise<boolean> {
    try {
      await this.ensureDir();
      await fs.writeFile(this.historyPath, JSON.stringify(history, null, 2), 'utf8');
      return true;
    } catch (error) {
      console.error('Failed to save history:', error);
      return false;
    }
  }

  async loadEnvironments(): Promise<EnvironmentsData> {
    try {
      if (existsSync(this.environmentsPath)) {
        const data = await fs.readFile(this.environmentsPath, 'utf8');
        return JSON.parse(data) as EnvironmentsData;
      }
    } catch (error) {
      console.error('Failed to load environments:', error);
    }
    return { environments: [], activeId: null };
  }

  async saveEnvironments(data: EnvironmentsData): Promise<boolean> {
    try {
      await this.ensureDir();
      await fs.writeFile(this.environmentsPath, JSON.stringify(data, null, 2), 'utf8');
      return true;
    } catch (error) {
      console.error('Failed to save environments:', error);
      return false;
    }
  }

  getStorageDir(): string {
    return this.storageDir;
  }
}
